server:
  servlet:
    context-path: /apps
  forward-headers-strategy: native

proxy:
  title: "Bioinformatics Core Shiny Apps"
  port: 8080
  landing-page: /
  template-path: /etc/shinyproxy/templates
  authentication: ldap
  ldap:
    url: ldaps://ldap.uchicago.edu:636/dc=uchicago,dc=edu
    manager-dn: uid=criucldap,ou=people,dc=uchicago,dc=edu
    manager-password: ${LDAP_MANAGER_PASSWORD}
    user-search-base: ou=people
    user-search-filter: (&(uid={0})(objectClass=person))
  docker:
    internal-networking: false
    url: http://localhost:2375
  specs:
    - id: test_yanli
      display-name: "test1 yan"
      description: "test demo with zhongyu, operated by Yan"
      logo-url: "/images/bioinfo_scientists.jpg"
      container-image: ghcr.io/zhongyuli2026/shiny-test1:latest
      port: 3838
    - id: scvizapp
      display-name: "scVizApp"
      description: "scRNASeq Visualization Application"
      logo-url: "/images/bioinfo_scientists.jpg"
      container-image: ghcr.io/zhongyuli2026/shiny-scvizapp:latest
      port: 3838
      container-volumes:
        - /srv/data/scrna_data/:/srv/shiny-server/data/
    - id: feavisapp
      display-name: "FeaVis App"
      description: "Functional enrichment analysis visualization application."
      container-image: ghcr.io/zhongyuli2026/shiny-feavisapp:latest
      port: 3838
      container-volumes:
        - /srv/data/feavis_data/:/srv/data/feavis_data/
    - id: tfheatmap
      display-name: "TFHeatmap"
      description: "Visualize potential master TFs and gene modules across pathways using DAP-seq TF target data and conservation scores."
      container-image: ghcr.io/zhongyuli2026/shiny-tfheatmap:latest
      port: 3838
